#
# IMPORTANT: these configuration is only used for integration and unit testing purposes.
# It should be overriden by your own application when using this library.
#

ig_trading_api:
  account_number_demo: "XXXXX"
  account_number_live: "XXXXX"
  # Only required for put_session_works integraton test. It must be associated
  # to the same running environment as the main account number.
  account_number_test: "XXXXX"
  api_key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  auto_login: true
  base_url_demo: "https://demo-api.ig.com/gateway/deal"
  base_url_live: "https://api.ig.com/gateway/deal"
  execution_environment: "DEMO" # LIVE / DEMO
  password: "your_password"
  session_version: 2
  username: "your_username"
